### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [weijia-cheng/procopius_the-secret-history_richard-atwater#1]
### colophon.xhtml:

- [x] Instead of saying "was published in the 6th century" it would be better to have "was completed in the 6th century", as it wasn't officially published until 1623.

- This isn't required, but I would also add CE or AD to "6th century" for clarity. Our collection has works that date around 6th century BC. I usually add an era label if the year is less than 1000.
 
### content.opf:

- [x] Add _Anecdotes_ as an alternative title.

**Comment by weijia-cheng** [comment]
Done!
